### ISSUE TITLE
docker-image resource not working properly on builds (and other minor problems)

### ISSUE THREAD

**Issue by grenzr** [anorsich/concourse-ansible-deploy#1]
Hi there,

I've been testing this with interest in AWS, but have hit a couple of problems.
The first problem is a missing `--work-dir` param in the worker template (something I intended to add in my fork for a forthcoming PR)

The second problem is `--peer-ip` and `--tsa-host` ip address params in the worker config aren't in my security group in AWS. However I don't really want non-public ports exposed this way, so I think an additional Ansible parameter to separate public and private ip's would be useful in the templates.

After fixing the above 2 manually, I was able to start up 

The third problems is when I try to use a docker-image resource on a build, but get endless `'waiting for docker to come up...'` messages.

After I used wsh to shell into the container trying to do this work, I went straight to the docker log file to find out whats going on:

```
/opt/concourse/worker/linux/depot/gm5j8f9vg95/bin/wsh --socket /opt/concourse/worker/linux/depot/gm5j8f9vg95/run/wshd.sock --user root
~ # cat /tmp/docker.log
time="2016-04-06T12:42:16.040462691Z" level=warning msg="devmapper: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option"
time="2016-04-06T12:42:16.040827522Z" level=error msg="There are no more loopback devices available."
time="2016-04-06T12:42:16.040903092Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback attach failed"
```

Have you hit this problem before? How did you manage to fix it?

Thanks,

Ryan

**Comment by anorsich** [comment]
Hi @grenzr!

I was not able to finish my Concourse setup due to a strict timeline on the project, but mostly likely going to give it another try soon, since I love ideas behind Concourse. 

I would love to accept any PR's which fixes the errors you mentioning and introduces another variable for private ip, which common thing not just on AWS, but on other cloud providers as well.  

Concerning docker-image resource I remember for sure that I was able to make a simple pipeline (git pull -> docker build -> docker push) working on local Concourse running inside of vagrant, but for some reason is stuck with the same pipeline on the instance deployed using concourse-bin. I see they are working hard and making a lot of releases, so perhaps issues I had gone now.

I would recommend filing your docker-image issue to either concourse or concourse-bin repo. They respond pretty fast and keen to help. 

Sorry for not being very helpful at the moment. Let's make it work :)

**Comment by grenzr** [comment]
Hi @anorsich 

Thanks for your quick reply :)
I love the ideas behind Concourse too, and have had it working perfectly too in Virtualbox, but not yet with the binaries.

I noticed concourse/bin repo has 1.0.1 release candidates available. I am happy to report I tried those and it worked perfectly! Yay :)

**Comment by grenzr** [comment]
Oh but wait... different problem now 'could not read file from tar' 

Probably related to this:
https://github.com/concourse/atc/blob/master/worker/image/fetcher.go#L218

**Comment by anorsich** [comment]
@grenzr I just updated vars to use latest 1.0.1 RC9 release. If you'll make it work that would be great to share your solution :)

**Comment by grenzr** [comment]
Still looking at this. I noticed the kernel I'm using on the latest 14.04 AMI in AWS is 3.13. Minimum requirement is 3.19 - I've upgraded as follows:

`sudo apt-get install linux-generic-lts-vivid`

This made the docker containers untar properly and return correctly!

**Comment by grenzr** [comment]
I'll make the appropriate changes in my fork now and PR it to you asap.

**Comment by grenzr** [comment]
See #2 :)

**Comment by anorsich** [comment]
@grenzr I just made you a collaborator on the project, so you can add/change things. I do not have plans to use concourse in next couple of months and hope to start use it for a next project :)

**Comment by grenzr** [comment]
oh cool thank you :)
I'll see about adding tests next.
